version: "3.3"

services:
    minecraft:
        build:
            context: .
        ports:
            - 25565:25565
            - 25575:25575
        container_name: "minecraft-server"
        volumes:
            - .server-data:/server
        restart: unless-stopped